import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Navbar from "../components/nav/navbar";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";
import { getVideos } from "../lib/videos";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const disneyVideos = getVideos()
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Nextflix</h1> */}
      <Navbar username="oloyedeoluwafemi22@gmail.com" />
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" size="large" videos={disneyVideos} />
        <SectionCards title="Disney" size="medium" videos={disneyVideos} />
        <SectionCards title="Disney" size="small" videos={disneyVideos} />
      </div>
    </div>
  );
}
